controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

create_post:
    path: /api/posts
    controller: App\Controller\CreatePostController
    methods: [POST]
